allow-shorthand: false

inherits:
  - strictness_veryhigh

ignore-patterns:
  - ^setup.py$

pylint:
  disable:
    - trailing-whitespace
    - missing-final-newline
    - too-few-public-methods
    - too-many-public-methods
    - deprecated-lambda
    - bad-builtin
    - star-args
    - global-statement
    - assignment-from-none
    - unused-format-string-key
    - W5103

  options:
    max-args: 8
    max-locals: 15
    max-returns: 6
    max-branches: 15
    max-statements: 60
    min-public-methods: 1
    max-public-methods: 20
    max-line-length: 120

pep8:
  options:
    max-line-length: 120
  disable:
    - E304
    - E265
    - E266
    - W291
    - W292
    - W391
    - W605
    - N811
    - N812
    - N813
    - N814

pyroma:
  disable:
    - PYR15
    - PYR18
    - PYR17

pep257:
  disable:
    - D400
    - D401
